TODO-57 переделал задачу в react
ZiminAlexander/to-do-project-frontend pull request #44
Opened 2023-04-04 18:37 UTC by ZiminAlexander

2023-04-05 17:28 UTC, NKBelousov requested changes

2023-05-01 14:00 UTC, ZiminAlexander commented on src/components/task-table/task-page.js
> +        <SearchForm updateTasksFromServer={updateTasksFromServer}
@NKBelousov поднял все методы, которые используют updateTasksFromServer

2023-05-04 21:54 UTC, NKBelousov requested changes

2023-05-04 21:54 UTC, NKBelousov commented on src/components/edit-window/edit-table/edit-table-box/close-edit-button/close-edit-button.js
> +      onClick={closeEditButtonCallback}
@ZiminAlexander я бы переименовал в что-то простое, обычно называют по аналогии с обычными событиями, например, `onClose`

2023-05-04 21:54 UTC, NKBelousov commented on src/components/edit-window/edit-table/edit-table-box/description-box/description-box.js
> +export const DescriptionBox = ({newDescription, setNewDescription}) => {
@ZiminAlexander тут тогда получится, например, `description` и `onChangeDescription`

2023-05-04 21:54 UTC, NKBelousov commented on src/components/edit-window/edit-table/edit-table-box/description-box/description-edit-box/edit-full-text-button/edit-full-text-button.js
> +export const EditFullTextButton = ({changeIsEditEnable}) => {
@ZiminAlexander когда есть какой-то флаг, который переключается туда-сюда, его часто называют `toggle` либо `toggleSomething`, в твоём случае получается типа `toggleIsEditable`

2023-05-04 21:54 UTC, NKBelousov commented on src/components/edit-window/edit-table/edit-table-box/edit-table-box.js
> +export const EditTableBox = ({newTitle, setNewTitle, newDescription,
@ZiminAlexander а что если вместо того, чтобы передавать и редактировать каждое поле будем передавать и редактировать объект, получится что-то типа `task, onChangeTask`

Сейчас получается что с каждым новым полем в компоненте добавляется 2 пропа, кажется может очень быстро вырасти их кол-во

2023-05-04 21:54 UTC, NKBelousov commented on src/components/task-table/new-task-form/new-task-area/new-task-area.js
> +    if (event.keyCode !== 13) {
@ZiminAlexander кажется удобнее через `event,code`

2023-05-04 21:54 UTC, NKBelousov commented on src/components/task-table/search-form/search-area/search-area.js
> +  const searchAreaElement = useRef(null);
@ZiminAlexander можешь рассказать зачем нужен этот реф?

2023-05-04 21:54 UTC, NKBelousov commented on src/components/task-table/task-page.js
> +    if (allTasks === null) {
@ZiminAlexander не очень хорошо что и данные, и ошибка загрузки хранятся в одной переменной

2023-05-04 21:54 UTC, NKBelousov commented on src/index.js
> +            <NotificationContext.Provider
@ZiminAlexander а зачем столько провайдеров?

2023-05-04 21:54 UTC, NKBelousov commented on src/components/task-table/task-page.js
> +import React, { useEffect, useState } from "react";
@ZiminAlexander давай попробуем разбить этот файл на несколько, кажется что тут много хелперов, которые не особо завязаны на сам компонент

2023-05-10 17:16 UTC, ZiminAlexander commented on src/index.js
> +            <NotificationContext.Provider
@NKBelousov они там, откуда нотификации вызываются. Можно убрать контекст и передавать в виде пропа или поднять все методы в index,js

2023-05-10 17:24 UTC, ZiminAlexander commented on src/components/task-table/search-form/search-area/search-area.js
> +  const searchAreaElement = useRef(null);
@NKBelousov c помощью этой ссылки я беру значение из поля поиска и обнуляю его по нажатию кнопки.
Можно попробовать убрать и скорректировать логику. Сейчас стейт меняется, если перестал печатать и сразу идёт запрос на сервер, а можно сделать, чтобы он непрерывно менялся, но вызывать эффект, когда перестал печатать.

2023-05-10 17:28 UTC, ZiminAlexander commented on src/components/edit-window/edit-table/edit-table-box/close-edit-button/close-edit-button.js
> +      onClick={closeEditButtonCallback}
@NKBelousov Это именно в локальных файлах? Или по всей программе?
Боюсь в task-page если сделать названия проще, можно запутаться

2023-05-10 17:39 UTC, ZiminAlexander commented on src/components/edit-window/edit-table/edit-table-box/description-box/description-edit-box/edit-full-text-button/edit-full-text-button.js
> +export const EditFullTextButton = ({changeIsEditEnable}) => {
@NKBelousov скорректировал

2023-05-10 17:48 UTC, ZiminAlexander commented on src/components/task-table/new-task-form/new-task-area/new-task-area.js
> +    if (event.keyCode !== 13) {
Скорректировал

2023-05-10 17:55 UTC, ZiminAlexander commented on src/components/task-table/task-page.js
> +    if (allTasks === null) {
@NKBelousov нужно сделать отдельную переменную для ошибки?
А когда нет задач по заданному фильтру или ещё не создали задачи - оставить в allTasks или перенести в ошибку?
Ошибку с задачами можно отображать как задачу или с помощью нотификации?

2023-05-10 19:09 UTC, ZiminAlexander commented on src/components/task-table/task-page.js
> +import React, { useEffect, useState } from "react";
@NKBelousov почти все методы - коллбэки. Насколько я понимаю, нужно выделить куски кода, которые не работают со стейтом или компонентами и убрать в отдельные файлы?

2023-05-10 19:16 UTC, ZiminAlexander commented on src/components/edit-window/edit-table/edit-table-box/edit-table-box.js
> +export const EditTableBox = ({newTitle, setNewTitle, newDescription,
@NKBelousov для editWindow можно что-то подобное придумать. А для остальных компонентов тоже нужно придерживаться такого подхода? Нужно ли передавать объект в компоненты поиска или создания?
<SearchForm setSearchAreaElement={setSearchAreaElement}
          clearSearchArea={clearSearchArea}
          searchAreaInputChange={searchAreaInputChange}
/>
<NewTaskForm submitTask={submitTask} />

2023-05-11 17:50 UTC, ZiminAlexander commented on src/components/edit-window/edit-table/edit-table-box/edit-table-box.js
> +export const EditTableBox = ({newTitle, setNewTitle, newDescription,
@NKBelousov собрал пропы в два объекта

2023-06-21 13:26 UTC, NKBelousov commented on src/components/loading-window/loading-window.js
> +    return(
@ZiminAlexander кажется созванивались по этой проблеме

2023-07-04 14:53 UTC, NKBelousov approved these changes

2023-07-05 17:34 UTC, merged